# Numpy 정리 #

## Numpy 시작 ##

In [4]:
# import numpy
import numpy as np

In [5]:
# 0으로 이루어진 ndarray 생성
np.zeros(3)

# 다차원 배열 생성도 가능
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 용어 ##
축(axis) : numpy에서의 차원
랭크(rank) : 축의 개수
Shape : 배열의 크기
size : 전체 원소의 개수

ex) 3 X 4 행렬의 랭크는 2, 
    0번 축의 길이는 3, 1번 축의 길이는 4
    배열의 shape은 (3, 4)
    배열의 size는 12

In [6]:
# 용어 실습

arr1 = np.zeros((3,4))
print(arr1)

print()

print(arr1.shape)

print()

print(type(arr1.shape)) # tuple 형식으로 반환

print()

print(arr1.ndim) # len(a.shape)와 같음

print()

print(arr1.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

(3, 4)

<class 'tuple'>

2

12


## 배열 다루기 ##

In [7]:
# N 차원 배열 생성
print(np.zeros((2, 3, 4,)))

print()

# 배열 타입
print(type(np.zeros((3,4))))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

<class 'numpy.ndarray'>


In [8]:
# 1로 이루어진 배열 생성
print(np.ones((2, 2)))

print()

# 특정 값으로 이루어진 배열 생성
print(np.full((3, 5), np.pi)) # 파이로 이루어진 행렬

print()

print(np.full((2, 2, 2), 500))


[[1. 1.]
 [1. 1.]]

[[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]]

[[[500 500]
  [500 500]]

 [[500 500]
  [500 500]]]


In [9]:
# 초기화되지 읺는 배열 생성
print(np.empty((2,2)))

[[1.0609979e-311 1.0609979e-311]
 [1.0609979e-311 1.0609979e-311]]


In [10]:
# 배열 생성 with list
np.array([
    [1, 2, 3, 4],
    [10 ,20, 30 ,40]
])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [11]:
# np.arage
# 파이썬 내장함수 range와 비슷함

print(np.arange(1, 5)) # 1 이상부터 5 미만까지 나열

print()

print(type(np.arange(1, 2))) # 타입은 1차원 ndarray

print()

print(np.arange(1, 5, 2)) # 건너뛰기


[1 2 3 4]

<class 'numpy.ndarray'>

[1 3]


In [12]:
# np.rand
# 0과 1사이의 랜덤한 부동 소수로 배열을 초기화
print(np.random.rand(3, 4))

print()

# np.randn
# 가우시안 분포에서 샘플링한 랜덤 부동 소수로 배열을 초기화
print(np.random.randn(3, 4))

print()

#np.randint
print(np.random.randint(1,3, (5, 5))) # 1이상부터 3 미만까지 랜덤 정수로 5X5배열 초기화 

[[0.32602167 0.77118445 0.33928321 0.83607257]
 [0.53197189 0.28579441 0.25761001 0.7107751 ]
 [0.67740177 0.16375473 0.38671346 0.58824663]]

[[-0.02097116  0.06665091 -0.10152726  0.29255412]
 [-0.7686134  -2.24379032  0.38195281  0.2939809 ]
 [-0.77777512 -1.1798253  -0.08665833 -1.05129022]]

[[1 2 1 2 2]
 [1 2 1 2 2]
 [1 1 2 2 1]
 [2 2 2 2 1]
 [1 1 2 1 1]]


In [13]:
#np.fromfunction
def ex_function(x, y, z):
    return x+10*y+100*z

np.fromfunction(ex_function, (2, 3, 4), dtype=np.int64)

array([[[  0, 100, 200, 300],
        [ 10, 110, 210, 310],
        [ 20, 120, 220, 320]],

       [[  1, 101, 201, 301],
        [ 11, 111, 211, 311],
        [ 21, 121, 221, 321]]], dtype=int64)

In [14]:
# dtype : 데이터 타입
# numpy의 ndarray에는 모든 원소가 동일한 type을 갖는다.
arr2 = np.arange(1,5)
print(arr2.dtype, arr2)

print()

arr3 = np.arange(1.0, 5.0)
print(arr3.dtype, arr3)

int32 [1 2 3 4]

float64 [1. 2. 3. 4.]


In [15]:
# type 지정
arr4 = np.arange(1, 5, dtype=np.complex64)
print(arr4.dtype, arr4)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [16]:
# itemsize : 각 아이템의 크기(Byte) 반환
arr5 = np.arange(1, 5, dtype=np.int64)
print(arr5.itemsize)

8


In [17]:
# shape : 배열 크기 지정
arr6 = np.arange(24)
print(arr6)
print("랭크 : ", arr6.ndim)
print(arr6.shape)
print()

arr6.shape = (3, 8)
print(arr6)
print("랭크 : ", arr6.ndim)
print(arr6.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
랭크 :  1
(24,)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
랭크 :  2
(3, 8)


In [18]:
# reshape : 배열 크기 변경
arr7 = arr6.reshape(4, 6)
print(arr7)
print("랭크 : ", arr7.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
랭크 :  2


In [19]:
# ravel : 모든 배열을 1차원으로 반환
print(arr7.ravel())

print()

# 원본이 변하지는 않음
print(arr7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## 배열 연산 ##

### 산술 연산 ###

In [20]:
# 일반적인 산술 연산자 모두 ndarray에서 사용이 가능함
arr1 = np.array([14, 23 ,32, 41])
arr2 = np.array([5, 6 ,7, 2])

print("arr1 + arr2 : ", arr1 + arr2)
print("arr1 - arr2 : ", arr1 - arr2)
print("arr1 * arr2 : ", arr1 * arr2)
print("arr1 / arr2 : ", arr1 / arr2)
print("arr1 // arr2 : ", arr1 // arr2)
print("arr1 % arr2 : ", arr1 % arr2)
print("arr1 ** arr2 : ", arr1 ** arr2)

arr1 + arr2 :  [19 29 39 43]
arr1 - arr2 :  [ 9 17 25 39]
arr1 * arr2 :  [ 70 138 224  82]
arr1 / arr2 :  [ 2.8         3.83333333  4.57142857 20.5       ]
arr1 // arr2 :  [ 2  3  4 20]
arr1 % arr2 :  [4 5 4 1]
arr1 ** arr2 :  [   537824 148035889         0      1681]


### 브로드캐스팅(Broadcasting) ###
일반적으로 numpy에서는 동일한 크기의 배열끼리의 산술연산이 가능하지만, 만약 크기가 맞지 않는 경우에는 아래와 같은 규칙을 적용한다.

#### 1. 배열의 랭크가 동일하지 않으면 랭크 맞춤을 위해 1을 추가한다. ####

In [21]:
arr3 = np.arange(5).reshape(1, 1, 1, 5)
print(arr3)
print("랭크 : ", arr3.ndim)

print()

arr4 = np.arange(5).reshape(5)
print(arr4)
print("랭크 : ", arr4.ndim)

print()

arr5 = arr3 + arr4 
# 위 연산에서 브로드캐스팅 발생 arr4.shape == (1, 1, 1, 5)
print(arr5)
print("랭크 : ", arr5.ndim)

[[[[0 1 2 3 4]]]]
랭크 :  4

[0 1 2 3 4]
랭크 :  1

[[[[0 2 4 6 8]]]]
랭크 :  4


#### 2. 특정 차원이 1인 배열은 그 차원에서 크기가 가장 큰 배열의 크기에 맞춰 동작한다.

In [22]:
arr6 = np.arange(6).reshape(2, 3)
print(arr6)

print()

arr7 = np.array([
    [100],
    [200]
])
print(arr7)

print()

arr8 = arr6 +arr7
print(arr8)

print()

arr9 = np.array([100, 200, 300])
print(arr9)

print()

arr10 = arr6 + arr9
print(arr10)




[[0 1 2]
 [3 4 5]]

[[100]
 [200]]

[[100 101 102]
 [203 204 205]]

[100 200 300]

[[100 201 302]
 [103 204 305]]


### 업캐스팅 ###
dtype가 다른 배열을 합칠 때 모든 값을 다룰 수 있는 type로 바꿔준다.

In [23]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

print()

k2 = np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)

print()

print((k1 + k2).dtype, k1+k2)

uint8 [0 1 2 3 4]

int8 [5 6 7 8 9]

int16 [ 5  7  9 11 13]


In [24]:
k3 = k1 + .5
print(k3.dtype, k3)

float64 [0.5 1.5 2.5 3.5 4.5]


In [25]:
m = np.array([20, -5, 30, 40])
print( m <[15, 16, 35, 36] )

print()

print(m < 25)

print()

[False  True  True False]

[ True  True False False]



In [26]:
# 평균 mean
arr1 = np.array([
    [-2.5, 3.1, 7],
    [10, 11, 12]
    ])
print(arr1)
print(arr1.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
6.766666666666667


## 함수 ##

In [27]:
# 다양한 함수들
for func in (arr1.min, arr1.max, arr1.sum, arr1.prod, arr1.std, arr1.var):
    print(f'{func.__name__} == {func()}')

min == -2.5
max == 12.0
sum == 40.6
prod == -71610.0
std == 5.084835843520964
var == 25.855555555555554


In [28]:
# 축(행 or 열) 선택해서 연산
arr2 = np.arange(24).reshape(2, 3, 4)
print(arr2)

print()

print(arr2.sum(axis=0))

print()

print(arr2.sum(axis=1))

print()

print(arr2.sum(axis=(0, 2)))

print()

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[12 15 18 21]
 [48 51 54 57]]

[ 60  92 124]



In [29]:
# 단항 일반 함수
arr3 = np.array([
    [-2.5, 3.1, 7],
    [10, 11, 12]
    ])

arr4 = np.square(arr3)


print(arr3)

print()

print(arr4)

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

[[  6.25   9.61  49.  ]
 [100.   121.   144.  ]]


In [30]:
print(arr3)

for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(arr3))

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


D:\cbhyconda\envs\mljnu\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """
D:\cbhyconda\envs\mljnu\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """


In [31]:
# 이항 일반 함수
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])

print(np.add(a, b)) # a + b 
print()
print(np.greater(a, b)) # a > b
print()
print(np.maximum(a, b))
print()
print(np.copysign(a, b)) # a 의 부호를 b 로 변환하는 함수

[ 3  6  2 11]

[False False  True False]

[2 8 3 7]

[ 1.  2. -3.  4.]


## 배열 인덱싱 && 슬라이싱 ##

### 1차원 배열 ###

In [33]:
# 1차원 배열은 파이썬 리스트와 비슷하게 사용할 수 있다.
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr1[3])

4


In [34]:
# 슬라이싱도 마찬가지
print(arr1[1 : 5])

[2 3 4 5]


In [42]:
# 차이점?

# 리스트는 불가능
lis2 = list(range(10))

try:
    lis2[2:5] = -1
except:
    print("오류")
    pass

# ndarray는 가능
arr1[2:5] = -1 
print(arr1)

오류
[ 1  2 -1 -1 -1  6  7  8  9]


In [43]:
# ndarray의 크기는 고정되어있기 때문에 끼워넣으면서 크기변경 불가능
try:
    arr1[1:2] = [1, 2, 3, 4, 5, 6]
except:
    print("안됨")
    pass

# 이것도 불가능
try:
    arr1[1:2] = [1, 2]
except:
    print("안됨")
    pass


안됨
안됨


In [47]:
# 원소 삭제도 불가능
try:
    del arr1[1]
except:
    print("안됨")
    pass

print()


# 전체 삭제는 가능
try:
    del arr1
except:
    print("안됨")
    pass
finally:
    try:
        print(arr1)
    except:
        print("삭제 확인")
        pass

안됨
안됨
삭제 확인
