# Merge to One CSV File Code #

## 이 코드는 전처리 과정이 다른 data를 사용한 경우, 기존 Sklearn에서 제공하는 Voting을 이용할 수 없기 때문에, 수작업으로 하드코딩한 작업물 입니다. ##

In [65]:
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf

In [66]:
r1 = pd.read_csv("r1.csv")
r2 = pd.read_csv("r2.csv")
r3 = pd.read_csv("r3.csv")
r4 = pd.read_csv("r4.csv")


from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)
r1_arr = ohe.fit_transform(r1[['method']])
r2_arr = ohe.fit_transform(r2[['method']])
r3_arr = ohe.fit_transform(r3[['method']])
r4_arr = ohe.fit_transform(r4[['method']])

In [67]:
arr = r1_arr + r2_arr +r3_arr + r4_arr

In [68]:
print(arr)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [0. 3. 1.]
 [0. 4. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [2. 0. 2.]
 [4. 0. 0.]
 [1. 0. 3.]
 [4. 0. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [1. 3. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [1. 3. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [0. 3. 1.]
 [0. 4. 0.]
 [4. 0. 0.]
 [1. 2. 1.]
 [4. 0. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [3. 1. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [1. 3. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [1. 3. 0.]
 [1. 3. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [1. 3. 0.]
 [0. 3. 1.]
 [1. 3. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [0. 4. 0.]
 [1. 3. 0.]
 [0. 4. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [4. 0. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [0. 4. 0.]
 [4.

In [69]:
a = []

In [70]:
for i in range(285):
    a.append(arr[i].argmax())

In [71]:
arra = np.array(a)

In [72]:
pds = pd.Series(arra).copy()

In [74]:
pds.to_csv('predict.csv',index=True)